-- C4/C3-amend: make the SQLite "INTEGER PRIMARY KEY AUTOINCREMENT" columns auto-generate on PG.
-- Uses START WITH max+1 (avoids pg_get_serial_sequence, which case-folds the table name).
DO $$
DECLARE t record; nxt bigint;
BEGIN
  FOR t IN (SELECT * FROM (VALUES
      ('audit_trail','id'),
      ('QR_code_assets','ID'),
      ('electrical_building_schema','row_id')
    ) AS v(tbl, col))
  LOOP
    IF EXISTS (SELECT 1 FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid
               WHERE c.relname=t.tbl AND a.attname=t.col AND a.attidentity <> '') THEN
      CONTINUE;  -- already identity
    END IF;
    EXECUTE format('ALTER TABLE %I ALTER COLUMN %I TYPE bigint USING %I::bigint', t.tbl, t.col, t.col);
    EXECUTE format('SELECT COALESCE(max(%I),0)+1 FROM %I', t.col, t.tbl) INTO nxt;
    EXECUTE format('ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                   t.tbl, t.col, nxt);
  END LOOP;
END $$;
